# Generated by Django 3.0.5 on 2021-01-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
