# Generated by Django 3.0.5 on 2021-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrainMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('brainID', models.IntegerField()),
                ('taskName', models.TextField()),
            ],
        ),
    ]
