# Generated by Django 3.0.5 on 2021-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepagemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbrainmap',
            name='brainID',
        ),
        migrations.AddField(
            model_name='userbrainmap',
            name='taskDescription',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbrainmap',
            name='taskName',
            field=models.CharField(max_length=200),
        ),
    ]
